=== StephaneMangin/MNCO/src/main/java/org/istic/mnco/TP6/sousbig/automate.dtd
<!ELEMENT automate   (actions, transitions, finaux, arret, alafin)>
<!ELEMENT actions      (#PCDATA)>
<!ELEMENT transitions       (trans*)>
<!ELEMENT trans      (de, a, sur, faire)>
<!ELEMENT de      (#PCDATA)>
<!ELEMENT a      (#PCDATA)>
<!ELEMENT sur      (#PCDATA)>
<!ELEMENT faire      (#PCDATA)>
<!ELEMENT finaux      (etat*)>
<!ELEMENT etat      (#PCDATA)>
<!ELEMENT arret      (#PCDATA)>
<!ELEMENT alafin      (#PCDATA)>

=== StephaneMangin/MNCO/src/main/java/org/istic/mnco/TP6/sousbig/automate.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE automate SYSTEM "automate.dtd">
<automate>
	<actions></actions>
	<transitions>
		<trans>
			<de>1..nEtats - 1</de><a>nEtats - 1</a>
			<sur>0..255</sur>			
			<faire>Vide</faire>
		</trans>
		<trans>
			<de>0</de><a>nEtats - 1</a>
			<sur>0..255</sur>			
			<faire>Erreur</faire>
		</trans>
		<trans>
			<de>0</de><a>1</a>
			<sur>'a'..'z'</sur>
			<faire>DebutIdf</faire>
		</trans>
		<trans>
			<de>1</de><a>1</a>
			<sur>'a'..'z'</sur>			
			<faire>SuiteIdfOuChiffre</faire>
		</trans>
	</transitions>
	<finaux>
		<etat>nEtats - 1</etat>		
	</finaux>
	<arret>surFinal</arret>
	<alafin>passerAuCrible</alafin>
</automate>
